[phases.setup]
nixPkgs = ['python311', 'postgresql_16.dev', 'gcc']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip'
]

[variables]
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
PIP_TIMEOUT = "1000"

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu",
    ". /opt/venv/bin/activate && pip install --prefer-binary --no-cache-dir --timeout=1000 -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn luki_memory.api.main:app --host 0.0.0.0 --port $PORT --workers 1"
